version: "3.9"
services:
  nginx:
    container_name: react-nginx
    build: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/usr/share/nginx/html
  app:
    container_name: react-app
    build: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/php/php.ini
      - ./backend:/var/www/html
