version: "3.9"
services:
  web:
    container_name: react-nginx
    build: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/usr/share/nginx/html

  app:
    container_name: react-app
    build: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/php/php.ini
      - ./backend:/var/www/html

  db:
    container_name: react-db
    build: ./docker/mysql
    ports:
      - 3306:3306
    volumes:
      - react-db-volume:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: react_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password

volumes:
  react-db-volume:
