version: "3.9"
services:
  nginx:
    container_name: react-nginx
    build: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/usr/share/nginx/html
